### ISSUE TITLE
These basemap tiles will no longer be available as of October 31, 2023

### ISSUE THREAD

**Issue by emilburzo** [AntoineMeler/Paraglidable#8]
Just a heads-up in case you've missed it: https://maps.stamen.com/stadia-partnership/

> If your current usage is less than 200,000 tiles / month—FREE for non-commercial use
> If your usage goes above 200,000 tiles / month or you are a commercial user—plans start at $20/month. The full pricing is [here](https://stadiamaps.com/pricing/).

![image](https://github.com/AntoineMeler/Paraglidable/assets/6228327/e74c02b9-ef51-43e7-a631-36a09a5eb15e)

**Comment by AntoineMeler** [comment]
Thanks Emil!
